- hosts: "{{ variable_host | default('elk7_env') }}"
  tasks:
    - name: remount /tmp/disk
      command: mount /tmp -o remount,exec

    - name: modify fstab file
      replace:
        path: /etc/fstab
        regexp: 'noexec'
        replace: ""


- hosts: "{{ variable_host | default('elk7_env') }}"
  serial: 1
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "2g"
    es_config:
      cluster.name: "monitoring-staging-cluster"
      network.host: _site_
      cluster.initial_master_nodes: "host1,host2,host3"
      discovery.seed_hosts: "host1:9300,host2:9300,host3:9300"
      http.port: 9200
      node.data: true
      node.master: true
      bootstrap.memory_lock: true
    es_data_dirs:
      - "/data01/elasticsearch/data/"
    #es_log_dir:
    #  - "/data01/elasticsearch/log/"
    es_plugins:
      - plugin: ingest-attachment
    es_use_repository: true
    es_add_repository: true
    es_version: "7.6.0"
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: password
    es_enable_auto_ssl_configuration: true
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_keystore: "files/certs/my-ca.p12"
    es_ssl_truststore: "files/certs/my-keystore.p12"
    es_ssl_keystore_password: ""
    es_ssl_truststore_password: ""
    es_validate_certs: no
